/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/weather/{date}": {
    /** Get the weather for a specific date */
    get: operations["getWeather"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    weather: {
      /** @enum {string} */
      summary: "sunny" | "cloudy" | "rainy" | "snowy";
      /**
       * @description Temperature in celsius 
       * @example 20
       */
      temperature: number;
      /**
       * @description Wind speed in km/h 
       * @example 12
       */
      windSpeed?: number;
    };
  };
  responses: never;
  parameters: {
    /** @description ISO date */
    date: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  /** Get the weather for a specific date */
  getWeather: {
    responses: {
      /** @description Success */
      200: {
        content: {
          "application/json": components["schemas"]["weather"];
        };
      };
      /** @description Invalid date ISO */
      422: never;
    };
  };
}
